[project]
name = "factorio-modding"
version = "2.0.0"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "gitpython>=3.1.43",
    "pillow>=11.0.0"
]

[tool.poetry]
package-mode = false
